import styles from "@/styles/Home.module.scss";

import Head from "next/head";
import MainLayout from "@/layout/main/MainLayout";
import PostCard from "@/components/postCard/PostCard";
import { GET } from "@/utils/api";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Next Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.App}>
        <MainLayout>
          <h1>Welcome!</h1>
          <PostCard data={{ title: "Un titolo per te" }} />
        </MainLayout>
      </main>
    </>
  );
}

// export async function getStaticProps() {
//   const res = await GET;
//   const posts = GET("posts");

//   return {
//     props: {
//       posts: posts.posts,
//     },
//   };
// }
